name: Build

run-name: ${{ github.actor }} is testing out build of pokecli

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends \
            build-essential
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: |
          make build

  build_for_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: ["1.22"]
    steps:
      - name: Install build dependencies
        run: brew install coreutils
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: |
          make build

  build_for_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ["1.22"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: |
          make build
