name: golangci-lint

run-name: ${{ github.actor }} is running static code analysis with golangci-lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.54
